# Generated by Django 5.1.6 on 2025-05-29 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="events/",
                        verbose_name="이미지",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="시작일")),
                ("end_date", models.DateTimeField(verbose_name="종료일")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="공개여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="작성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "이벤트",
                "verbose_name_plural": "이벤트",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="notices/",
                        verbose_name="이미지",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="공개여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="작성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "건강관리"),
                            ("feeding", "사료/영양"),
                            ("training", "훈련/교육"),
                            ("grooming", "미용/관리"),
                            ("behavior", "행동/심리"),
                            ("emergency", "응급처치"),
                            ("others", "기타"),
                        ],
                        default="others",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="tips/", verbose_name="이미지"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="공개여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="작성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "생활백서",
                "verbose_name_plural": "생활백서",
                "ordering": ["-created_at"],
            },
        ),
    ]
