# Generated by Django 5.1.6 on 2025-05-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tips",
            name="category",
        ),
    ]
