# Generated by Django 5.2.1 on 2025-05-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_remove_tips_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tips",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "털뭉치들",
                "verbose_name_plural": "털뭉치들",
            },
        ),
    ]
