# Generated by Django 5.2.1 on 2025-06-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_event_image_url_notice_image_url_tips_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="내용"),
        ),
    ]
