# Generated by Django 5.0.6 on 2025-06-17 06:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0005_alter_event_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="내용"),
        ),
    ]
