# Generated by Django 5.2.3 on 2025-07-01 06:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_alter_notice_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="내용"
            ),
        ),
        migrations.AlterField(
            model_name="tips",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="내용"),
        ),
    ]
