# Generated by Django 5.1.6 on 2025-05-29 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("internal", "내과"),
                            ("surgery", "외과"),
                            ("dental", "치과+안과"),
                        ],
                        default="internal",
                        max_length=20,
                        verbose_name="진료과목",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cases/",
                        verbose_name="대표 이미지",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="공개여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="작성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "치료케이스",
                "verbose_name_plural": "치료케이스",
                "ordering": ["-created_at"],
            },
        ),
    ]
