# Generated by Django 5.2.1 on 2025-06-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalcase",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="이미지를 클릭했을 때 이동할 URL을 입력하세요",
                null=True,
                verbose_name="이미지 링크 URL",
            ),
        ),
    ]
