# Generated by Django 5.2.3 on 2025-07-01 06:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_medicalcase_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalcase",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name="내용"),
        ),
    ]
